version: "3.8"

services:
  my_backend:
    image: movie-night
    build: .
    container_name: backend_service
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_URI=${DATABASE_URL}
      - PASSWORD_EMAIL=${PASSWORD_EMAIL}
      - USER_EMAIL=${USER_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - API_KEY_SEPAY=${API_KEY_SEPAY}
      - KEY1=${KEY1}
      - KEY2=${KEY2}
      - APP_ID=${APP_ID}
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo_service
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - my_backend

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
